//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSTicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Id { get; set; }
        public int Map_Id { get; set; }
        public string Name { get; set; }
        public string C_left { get; set; }
        public string C_top { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public decimal Price { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual Member Member { get; set; }
    }
}
